# EJEMPLO DE CONFIGURACIÓN DE SECRETS PARA STREAMLIT CLOUD
# 
# INSTRUCCIONES:
# 1. Ve a tu app en Streamlit Cloud
# 2. Haz clic en "Settings" (⚙️)
# 3. Selecciona "Secrets"
# 4. Copia y pega EXACTAMENTE el contenido de abajo
# 5. Reemplaza "tu_consumer_key" y "tu_consumer_secret" con los valores reales
# 6. Haz clic en "Save"
# 7. Reinicia tu app

# API Credentials - OroColmbia
OROCOLOMBIA_URL = "https://orocolombia.co/wp-json/wc/v3/products"
OROCOLOMBIA_CONSUMER_KEY = "ck_865f2431376662f2bff8e2fdca6a933869805784"
OROCOLOMBIA_CONSUMER_SECRET = "cs_b4d4ae6ce65cfa4300464afa935cc708398b90b4"

# API Credentials - GrupoFelmel  
GRUPOFELMEL_URL = "https://app.grupofelmel.com/wp-json/wc/v3/products"
GRUPOFELMEL_CONSUMER_KEY = "ck_ea825feef0c11159e9c95c4e410a76f800f4c38f"
GRUPOFELMEL_CONSUMER_SECRET = "cs_693ed6a9afb56a24d1c55fcbeb39f3bd2423818d"

# Application Settings
PRODUCTS_PER_PAGE = 100
CACHE_DURATION_MINUTES = 30
DISCOUNT_PERCENTAGE = 35